### ISSUE TITLE
How to quantify reliability of workers?

### ISSUE THREAD

**Issue by jiqicn** [EyeofBeholder-NLeSC/play-around-sample-set#1]
In the dataset, we only have the assessment of the statements by experts as the ground truth. Based on this, one measure of worker reliability is the assessment error, which is the absolute difference between doc_ground_truth_value and overall_truthfulness_value. But not sure if this is the best way.

**Comment by dafnevk** [comment]
Note that this 'error score' would calculate the reliability on a specific statement. That is very useful to then compare in relationship with e.g. the text of the statement and the assesments of the different dimension.

For a specific worker, you could then look at the distribution of errors for that worker, because they usually assess multiple statements. Then you can look at the relationship between e.g. education level and average error.

**Comment by jiqicn** [comment]
Indeed, I tried out the mean squared error of assessment for a single worker yesterday and got some results. 

My concern now, particularly regarding the IPM dataset, is that there is no clear way to evaluate the reliability of workers on different dimensions of assessment, since we don't have the ground truth data for that. However, as Davide suggested that specific dimensions may have a stronger correlation to the worker profile data than to the ground truth. Have no idea what the ontology that Davide is working on looks like, so not sure if all the future datasets will also include those dimensions of assessment.

**Comment by jiqicn** [comment]
The conclusion is that there is no way to validate workers' assessment on different dimensions, since we don't have the ground truth data for that. Instead, it would be nice to aggregate worker profile data on those dimensions and see if there is any patterns there.

**Comment by davideceolin** [comment]
Correct, that is a problem we have. In the paper, we looked at how to
combine the multiple dimensions in order to predict the only one for which
we had a ground truth. However, the quality dimensions are meant to
identify different aspects of quality, not necessarily correlated with
overall truthfulness. We are planning on collecting expert-provided
assessments on the dimensions but still, different experts with different
backgrounds might disagree on the ratings. This is still an open issue.

Il giorno gio 17 mar 2022 alle ore 10:26 Ji Qi ***@***.***>
ha scritto:
